In [6]:
import numpy as np

<h1>creation of 3D array</h1>

In [15]:
#arr1D = [1,2,3]
#arr2D = [[1,2,3],[1,2,3],[1,2,3]] # [1D,1D,1D]
arr3D = [[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]] #[2D,2D,2D,2D]

In [16]:
arr = np.array(arr3D)
arr

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [17]:
arr.ndim

3

In [12]:
arr3 = np.random.randint(1,200,(3,5,3))
arr3
#  (3,5,3) (table,row,column)

array([[[ 61, 154, 174],
        [124, 195, 181],
        [ 85,  65, 110],
        [ 11, 181,  34],
        [ 90,  79,  69]],

       [[ 65,  46,  93],
        [ 18,  66,   9],
        [173,  73, 194],
        [ 87,  31, 142],
        [184,  84,  98]],

       [[192, 169, 144],
        [ 22, 117, 108],
        [166, 144, 197],
        [114, 164,  56],
        [ 85, 163,  40]]], dtype=int32)

In [19]:
arr.shape

(2, 3, 3)

In [26]:
arr3[1,4,0:3]

array([184,  84,  98], dtype=int32)

In [27]:
arr3[2,0:2,1:3]

array([[169, 144],
       [117, 108]], dtype=int32)

In [36]:
arr3[-3:,-5,-3:]


array([[ 61, 154, 174],
       [ 65,  46,  93],
       [192, 169, 144]], dtype=int32)

In [37]:
arr3[0:,0]

array([[ 61, 154, 174],
       [ 65,  46,  93],
       [192, 169, 144]], dtype=int32)

In [39]:
arr = np.array([9,7,8])
arr

array([9, 7, 8])

In [41]:
#min(arr) # minimum 
max(arr) # maximum

np.int64(9)

In [43]:
np.mean(arr) # average

np.float64(8.0)

In [44]:
np.sum(arr) # total sum

np.int64(24)

In [45]:
np.argmin(arr)
# argmin returns index of minimum item in the array

np.int64(1)

In [46]:
np.argmax(arr)
# argmax returns indec of maximum item

np.int64(0)

In [48]:
arr.sort() # ascending order sort by default
arr

array([7, 8, 9])

In [51]:
arr[::-1] 
# decending order sort

array([9, 8, 7])

<h1>Pandas</h1>

In [52]:
import pandas as pd

In [61]:
## what is dataframe
## how we can data frame

#dictionary
dt = {"Name":['ritu','taniya','abhishek','tanmay','mayank'],
      "Branch":['it','cse','it','ece','cse'],
      "Class": [2,3,4,1,2],
      "City":['jaipur','agra','vridavan','mathura','gokul']} 
dt

{'Name': ['ritu', 'taniya', 'abhishek', 'tanmay', 'mayank'],
 'Branch': ['it', 'cse', 'it', 'ece', 'cse'],
 'Class': [2, 3, 4, 1, 2],
 'City': ['jaipur', 'agra', 'vridavan', 'mathura', 'gokul']}

In [65]:
# np.array()
df = pd.DataFrame(dt)
df

Name Branch  Class      City
0      ritu     it      2    jaipur
1    taniya    cse      3      agra
2  abhishek     it      4  vridavan
3    tanmay    ece      1   mathura
4    mayank    cse      2     gokul

In [66]:
type(df)

pandas.core.frame.DataFrame

In [67]:
## series
df['Name']

0        ritu
1      taniya
2    abhishek
3      tanmay
4      mayank
Name: Name, dtype: object

In [68]:
type(df['Name'])

pandas.core.series.Series

In [70]:
#categorial
df.dtypes

Name      object
Branch    object
Class      int64
City      object
dtype: object

In [71]:
df.shape
# 5 ==> rows
# 4 ==> columns

(5, 4)

In [72]:
df.Name

0        ritu
1      taniya
2    abhishek
3      tanmay
4      mayank
Name: Name, dtype: object

In [83]:
df[['City','Name','Branch']]

City      Name Branch
0    jaipur      ritu     it
1      agra    taniya    cse
2  vridavan  abhishek     it
3   mathura    tanmay    ece
4     gokul    mayank    cse

In [92]:
# df[1:3]
# df[1:2]
df[1:-3]

Name Branch  Class  City
1  taniya    cse      3  agra

In [96]:
#df[1:3,0:2]
df[1:3][['Name','Branch']]

Name Branch
1    taniya    cse
2  abhishek     it

In [104]:
## LOC & ILOC
df.loc[1:2,['Name','Branch']]

Name Branch
1    taniya    cse
2  abhishek     it

In [105]:
df.iloc[1:3,0:2]

Name Branch
1    taniya    cse
2  abhishek     it

In [106]:
df.loc[3:4,['Branch','Class','City']]

Branch  Class     City
3    ece      1  mathura
4    cse      2    gokul

In [107]:
df.iloc[1:3,2:]

Class      City
1      3      agra
2      4  vridavan