In [1]:
import numpy as np

In [2]:
#creation of array 1D
arr = np.array([25,41,66,63,85,74])
arr 

array([25, 41, 66, 63, 85, 74])

In [3]:
type(arr)
#ndarray ==> n dimensional array

numpy.ndarray

In [4]:
arr.size  #no.of item

6

In [5]:
len(arr) #

6

In [6]:
arr.ndim #to check the array dimension

1

In [16]:
arr = np.array([25, 41, 66, 63, 85, 74,25.01,'upflairs',True])
arr
## similar type item stored
## array similar item 

array(['25', '41', '66', '63', '85', '74', '25.01', 'upflairs', 'True'],
      dtype='<U32')

In [15]:
arr.dtype

dtype('<U32')

In [12]:
print(np.__version__)

2.0.0


In [17]:
arr = np.array([25, 41, 66, 63, 85, 74])
arr

array([25, 41, 66, 63, 85, 74])

In [18]:
arr[-1]

np.int64(74)

In [22]:
arr[2:4:] #start = 0, stoping = end, jump = 1

array([85, 74])

In [23]:
arr[-1] = 500 #replace or update

In [24]:
arr

array([ 25,  41,  66,  63,  85, 500])

In [25]:
arr + 2
#increment or addition in item of 2

array([ 27,  43,  68,  65,  87, 502])

In [26]:
arr * 2
#multiplication in items by 2

array([  50,   82,  132,  126,  170, 1000])

<h1>2-D Arrays</h1>

In [27]:
#2-D arrays
ls = [[1,2,3],
      [4,5,6],
      [7,8,9]]
ls

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [28]:
type(ls)

list

In [29]:
ls[0]

[1, 2, 3]

In [30]:
arr2 = np.array(ls)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
arr2.shape 
# (3,3)
# 3 rows, 3 columns

(3, 3)

In [36]:
arr2[0] # to fetch single row

array([1, 2, 3])

In [39]:
arr2[0:2] #to fetch multiple rows

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
arr2[1,1:3]

array([5, 6])

In [46]:
arr2[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [53]:
# 9 = 90
arr2[-1,-1] = 90
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 90]])

In [54]:
arr = np.random.randint(1,200,500)
arr
#single dimension array

array([ 96,  26,  97,  94,  66, 183,  35, 195,  46, 171,  97, 108,   5,
        86, 116,   1,  57, 195, 122, 155, 190, 124,  63,  76, 129, 108,
        11,  18,  31,   8,  91,  98,  13,  24, 144, 156, 129,  77, 199,
       140, 133,   4, 107,  88,  92,  79, 186, 168,  74, 157,   7, 124,
        48, 151,  26, 185, 191,  92,  33, 123,  74, 118, 168, 128,  79,
        13, 107,  12,  91,  84,  35, 107,  15,   8,  95, 116,  79,  21,
       101, 109, 197, 135, 191, 188, 192, 177,  85, 125, 126,  33, 138,
        57, 103,  91, 106, 153, 107, 169,  21,  36, 178,  26, 191, 122,
        19, 117,  65,  87, 111,  11,  81,   2,  52, 153,  74,  91, 153,
       125,  28, 166, 144,  64,  91,  79,  34,  69,  71, 126,  90, 184,
        97, 137, 128, 144,  49, 119,  27, 102,  37,   8, 142,  26,  53,
        24, 115, 178,  45,  78,  53, 188,   8,  20,  27,  27, 148, 160,
        98, 101, 115,  65,  93,  35, 159, 166, 161, 157, 127,  27, 136,
         8,  23, 182, 117,  89,  51, 109,  26,  98,  12,  85,  4

In [68]:
#arr filter all that item that are less than equal to 100
# method 1:-
# np.sum(arr<=100)

#  method 2:-
# for i in arr:
#     count =0
#     if(i<=100):
#      count+=1
#     print(count)

arr[arr<=100]

array([96, 26, 97, 94, 66, 35, 46, 97,  5, 86,  1, 57, 63, 76, 11, 18, 31,
        8, 91, 98, 13, 24, 77,  4, 88, 92, 79, 74,  7, 48, 26, 92, 33, 74,
       79, 13, 12, 91, 84, 35, 15,  8, 95, 79, 21, 85, 33, 57, 91, 21, 36,
       26, 19, 65, 87, 11, 81,  2, 52, 74, 91, 28, 64, 91, 79, 34, 69, 71,
       90, 97, 49, 27, 37,  8, 26, 53, 24, 45, 78, 53,  8, 20, 27, 27, 98,
       65, 93, 35, 27,  8, 23, 89, 51, 26, 98, 12, 85, 41, 10, 90, 64, 52,
       17, 18, 28, 16, 56, 32,  2,  2, 13, 92, 18, 45, 28, 15, 82, 51, 85,
       64, 94,  8, 67, 91, 53, 13, 96, 42, 48, 90, 87, 87, 20, 50,  3, 50,
        4, 39, 47, 37, 82, 56, 77, 55, 25,  7, 41, 95, 30, 70, 54, 84, 18,
       56,  2, 47, 89, 76, 12, 71, 44, 34, 71, 62, 81, 84, 14, 58, 56, 92,
       22,  4, 91, 30, 75,  8, 46,  5, 60, 49, 68, 35, 82,  9, 66, 35, 52,
       93, 42,  5, 20, 61, 46, 88, 82, 11, 69, 37,  2, 16, 27, 12, 33, 37,
       92,  9, 61, 63, 26, 67, 59, 15, 67, 12, 51, 88, 38,  3, 70, 38, 24,
       80, 25, 96, 80, 51

In [67]:
arr[arr<=100].size #total items

253

In [69]:
arr[arr<=100].shape

(253,)

In [70]:
arr2 = np.random.randint(1,200,(10,5))
arr2
#2 D random generate

array([[159,   6,  70, 184,  16],
       [  7, 150,  94,   3,  61],
       [ 78,  16, 193, 154, 121],
       [  7, 159,  77,  26,  81],
       [ 45, 186, 136,  15,  70],
       [126,  60,  71,  39, 147],
       [ 17,  42, 159, 191,   8],
       [109, 176, 197, 142, 115],
       [199,  70,  89,  10,  79],
       [175, 136, 104,  70, 117]], dtype=int32)

In [71]:
arr2 = np.random.randint(1,200,(10,6,3))
arr2

array([[[198,  62,  53],
        [168, 106,  70],
        [187,  75, 167],
        [ 84,  83,  21],
        [196,  46, 135],
        [114, 169, 162]],

       [[  7,  24, 133],
        [ 61,  59,  84],
        [ 22,   7, 132],
        [158, 134, 116],
        [ 80, 169, 136],
        [ 77,  57,  42]],

       [[144, 155,  86],
        [ 74, 175,  41],
        [183, 120, 182],
        [184,  65,  83],
        [197, 181,  77],
        [181,  20, 134]],

       [[146, 156,  12],
        [188,   3, 150],
        [187, 170,  73],
        [148, 104,  54],
        [ 51,  48, 186],
        [139, 185, 182]],

       [[ 17, 139,  86],
        [189,  87,  69],
        [ 28,  42,  38],
        [108, 170,  26],
        [170,  21,  12],
        [ 70,  97, 121]],

       [[186,  52, 108],
        [ 68, 165,  99],
        [ 72,  73, 152],
        [186, 125,   8],
        [197,  60, 120],
        [166, 172,  20]],

       [[ 19,  87, 174],
        [ 37, 148, 123],
        [173, 136, 106],
        [  5,

In [73]:
arr =np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [75]:
arr = np.zeros((10,5))
arr
# 2D 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [76]:
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [77]:
arr = np.ones((10,5))
arr
#2D

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [78]:
ls = [0,1,2,3,4,5,6,7,8,9]
ls

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [81]:
ls = list(range(10))
ls

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [84]:
#arr = np.arange(10)
#arr = np.arange(5,100)
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
       73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
       90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [101]:
arr = np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [104]:
arr.reshape(10,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [105]:
arr.reshape(3,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59]])