<h2>Numpy Library :-</h2>

NumPy is an essential library for scientific computing in Python, renowned for its robust features and capabilities.

It supports large, multi-dimensional arrays and matrices and provides a comprehensive suite of mathematical functions to operate on these arrays.

One of NumPy's key advantages is its ability to perform arithmetic operations on arrays of varying shapes and sizes without the need for explicit reshaping. This feature simplifies and streamlines the code, making it more intuitive.

NumPy is the foundation for many other scientific computing and data analysis libraries, including SciPy, Pandas, Matplotlib, and Scikit-Learn. This ensures compatibility and seamless integration across different tools.

Moreover, NumPy arrays are memory-efficient.

The library also includes essential functions for linear algebra, Fourier transforms, and random number generation, making it indispensable for numerous scientific and engineering applications.

In [136]:
# To Download numpy library --> pip install numpy (write in command prompt)
# Import the numpy library as np

import numpy as np

<h4>1-Dimension Array :-</h4>

In [137]:
# Creation of array 1D
arr = np.array([52,14,36,55,58,47])
arr

array([52, 14, 36, 55, 58, 47])

In [138]:
type(arr) # ndarray --> n dimensional array

# type() function is used to determine the type of an object.

numpy.ndarray

In [139]:
arr.dtype
# The dtype attribute of a NumPy array is used to determine the type of elements stored in the array.

dtype('int64')

In [140]:
arr.size #  The size attribute of an array returns the total number of elements in the array

6

In [141]:
len(arr) # The len() function is a built-in Python function used to get the number of items in a container

6

In [142]:
arr.ndim # The ndim attribute is used to determine the number of dimensions of an array. 

1

<h5>Indexing in 1-D Array:-</h5>

Indexing in a 1D NumPy array is similar to indexing in standard Python lists. 

In [143]:
# Creating a 1D NumPy array
arr = np.array([11, 22, 33, 44, 55])

# Accessing elements
print(arr[0])  # Output: 11
print(arr[2])  # Output: 33

11
33


In [144]:
# Modifying elements
arr[1] = 25
print(arr)  # Output: [11 25 33 44 55]

[11 25 33 44 55]


In [145]:
# Slicing elements
print(arr[1:4])  # Output: [25 33 44]
print(arr[:3])   # Output: [11 25 33]
print(arr[::2])  # Output: [11 33 55]
print(arr[-3:])  # Output: [33 44 55]  (slicing with negative index)

[25 33 44]
[11 25 33]
[11 33 55]
[33 44 55]


In [146]:
# The numpy.random.randint() function in NumPy is used to generate random integers within a specified range.
arr = np.random.randint(1,200,500)
print(arr)

[ 36 187 141  20 117  77  92 147 180 133  11 196 192 128  87 135 181 134
 199 113 147  17 103 157  22 135  54 140 189  18 171   7  16 154   9 130
 151  22 158 176 143  50 182 176   8 140 197  25  99 169  38  33 101 191
  63  19  21  37 117 180  50 161   1  47  24  35  59 181 103 154  71  59
  95 121  25  35  30  26 196  24  66 134  84 192 140 126  50  45 185  69
 145 186 194 102 125 149 174 185  99  27  42 186  63 165 130  31 120 126
 192  36 113 184  68 141 185 125  25  28 119  15  91   1  19  31 186 155
 138  61 199  15  38 100 111 168 159  55  39  70 186 149  40  23  63 113
  22 197  29  52  74 195  38 190 124   1 120 160 113 149  10 127 104  26
 142 178 140 142  92   5  29  47 193  86  53  69 133  69 190  89 168 159
   3  31 114  39  72  83  65  66 141  36 143 145  76 146  70 143 149  23
  67  91  38   2  63 179 145 111  80 138  65  91  79 133 139  20  53 178
 188 150 139 100 169  11  75  52 157 104 196  31 118  34  41  93  42  39
 155  16  14 126  62  87  42 194 110  46 140  30 10

<h4>2-Dimension Array :-</h4>

2D arrays (also known as matrices) in NumPy is a common task in scientific computing and data analysis. 

NumPy provides a range of functionalities to create, manipulate, and perform operations on 2D arrays.

In [147]:
# Creating a 2D NumPy array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [148]:
# Accessing elements
print("Element at (0, 0):", arr2d[0, 0])  # Output: 1
print("Element at (1, 2):", arr2d[1, 2])  # Output: 6

Element at (0, 0): 1
Element at (1, 2): 6


In [149]:
# Modifying elements
arr2d[1, 2] = 20
print("Modified 2D Array:")
print(arr2d)

Modified 2D Array:
[[ 1  2  3]
 [ 4  5 20]
 [ 7  8  9]]


In [150]:
# Slicing rows
print("First two rows:")
print(arr2d[:2])

First two rows:
[[ 1  2  3]
 [ 4  5 20]]


In [151]:
# Slicing columns
print("First two columns:")
print(arr2d[:, :2])

First two columns:
[[1 2]
 [4 5]
 [7 8]]


In [152]:
# Transposing the array
print("Transposed Array:")
print(arr2d.T)

Transposed Array:
[[ 1  4  7]
 [ 2  5  8]
 [ 3 20  9]]


In [153]:
# Summing all elements
print("Sum of all elements:", np.sum(arr2d))

Sum of all elements: 59


In [154]:
# Element-wise operations
print("Element-wise multiplication:")
print(arr2d * 2)

Element-wise multiplication:
[[ 2  4  6]
 [ 8 10 40]
 [14 16 18]]


In [155]:
# Matrix multiplication
arr2d_2 = np.array([[1, 2], [3, 4], [5, 6]])
print(np.dot(arr2d, arr2d_2))

[[ 22  28]
 [119 148]
 [ 76 100]]


<h4>3-Dimension Array :-</h4>

3-dimensional (3D) arrays in NumPy involves similar concepts to working with 2D arrays but adds an additional dimension for more complex data structures.

In [156]:
arr3 = np.random.randint(1,200,(3,5,3))

In [157]:
# The shape attribute of an array provides a tuple representing the dimensions of the array.

arr3.shape # (table, row, column)

(3, 5, 3)

In [158]:
# Creating a 3D NumPy array
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], 
                  [[7, 8, 9], [10, 11, 12]], 
                  [[13, 14, 15], [16, 17, 18]]])

# Accessing specific elements
print(arr3d[0, 0, 0])  # Output: 1
print(arr3d[1, 1, 2])  # Output: 12
print(arr3d[2, 1, 1])  # Output: 17

1
12
17


<h3>Numpy Functions :-</h3>

In [159]:
# The zeros() function in NumPy is used to create an array filled with zeros.

arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [160]:
arr = np.zeros((10,5)) # 10 row 5 column with item = 0
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [161]:
# The ones() function in NumPy is used to create an array filled with ones.

arr = np.ones((10,5)) # 10 row 5 column with item = 1
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [162]:
# The arange() function in NumPy is used to create arrays with evenly spaced values within a specified range.
# numpy.arange(start, stop, step)

np.arange(10) # creates array from range 0-18
# creates always 1D array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [163]:
arr = np.arange(60)
arr # 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [164]:
# The reshape() function in NumPy is used to change the shape of an existing array without modifying its data.
arr = arr.reshape(6,10) # 1D --> 2D
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [165]:
arr = np.array([1,2,4,3])
np.max(arr) # used to find the maximum value in an array.

np.int64(4)

In [166]:
np.min(arr) # used to find the minimum value in an array.

np.int64(1)

In [167]:
np.sum(arr) # uused to calculate the total of array elements along a specified axis or across the entire array.

np.int64(10)

In [168]:
np.argmin(arr) # returns the index position of the minimum item

np.int64(0)

In [169]:
np.argmax(arr) # returns the index position of the maximum item

np.int64(2)

In [170]:
# used to arrange the elements of an array along a specified axis. It returns a sorted version of the array.
arr.sort() # Ascending order
arr

array([1, 2, 3, 4])

In [171]:
arr[::-1] # Descending order

array([4, 3, 2, 1])